=== gvgreat/hrillekha/crown/retail/crown-retail/src/main/java/com/techlords/crown/mvc/reports/config/crown-report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.techlords.com/crown-report" xmlns:tns="http://www.techlords.com/crown-report"
	elementFormDefault="qualified">
	<xs:element name="crown-report">
		<xs:annotation>
			<xs:documentation>Crown Report Schema Definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="bean-name" nillable="false" maxOccurs="1"
					type="xs:string" />
				<xs:element name="title" nillable="false" maxOccurs="1"
					type="xs:string" />
				<xs:element name="sub-title" nillable="false" maxOccurs="1"
					type="xs:string" />
				<xs:element name="margin" nillable="false" maxOccurs="1"
					type="xs:int" />
				<xs:element name="detail-height" nillable="false" maxOccurs="1"
					type="xs:int" />
				<xs:element ref="tns:column-params" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<!-- COLUMN-PARAMS -->
	<xs:element name="column-params">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="column-name" nillable="false"
					maxOccurs="1" type="xs:string" />
				<xs:element name="column-title" nillable="false"
					maxOccurs="1" type="xs:string" />
				<xs:element name="class-name" nillable="false" maxOccurs="1"
					type="xs:string" />
				<xs:element name="column-width" nillable="false"
					maxOccurs="1" type="xs:int" />
				<xs:element name="criteria-column" minOccurs="0" maxOccurs="1" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gvgreat/hrillekha/crown/retail/crown-retail/src/main/java/com/techlords/crown/mvc/reports/config/stolen-stock-report.xml
<?xml version="1.0" encoding="UTF-8"?>
<crown-report xmlns="http://www.techlords.com/crown-report"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.techlords.com/crown-report crown-report.xsd ">
	<bean-name>StolenStockBO</bean-name>
	<title>Stolen Stock Report</title>
	<sub-title>Stolen Stock Report for all warehouses</sub-title>
	<margin>20</margin>
	<detail-height>15</detail-height>
	<column-params>
		<column-name>warehouseName</column-name>
		<column-title>Warehouse Name</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>70</column-width>
		<criteria-column>true</criteria-column>
	</column-params>
	<column-params>
		<column-name>itemName</column-name>
		<column-title>Item Name</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>70</column-width>
	</column-params>
	<column-params>
		<column-name>stolenItemQty</column-name>
		<column-title>Stolen Item Qty</column-title>
		<class-name>java.lang.Integer</class-name>
		<column-width>70</column-width>
	</column-params>
	<column-params>
		<column-name>stolenUOMQty</column-name>
		<column-title>Stolen UOM Qty</column-title>
		<class-name>java.lang.Integer</class-name>
		<column-width>70</column-width>
	</column-params>
	<column-params>
		<column-name>stolenDate</column-name>
		<column-title>Stolen Date</column-title>
		<class-name>java.util.Date</class-name>
		<column-width>70</column-width>
	</column-params>
	<column-params>
		<column-name>createdBy</column-name>
		<column-title>Created By</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>70</column-width>
	</column-params>
</crown-report>

=== gvgreat/hrillekha/crown/retail/crown-retail/src/main/java/com/techlords/crown/mvc/reports/config/stock-report.xml
<?xml version="1.0" encoding="UTF-8"?>
<crown-report xmlns="http://www.techlords.com/crown-report"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.techlords.com/crown-report crown-report.xsd ">
	<bean-name>WarehouseStockBO</bean-name>
	<title>Stock Report</title>
	<sub-title>Stock Report for all warehouses</sub-title>
	<margin>20</margin>
	<detail-height>15</detail-height>
	<column-params>
		<column-name>warehouseName</column-name>
		<column-title>Warehouse Name</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>85</column-width>
		<criteria-column>true</criteria-column>
	</column-params>
	<column-params>
		<column-name>itemName</column-name>
		<column-title>Item Name</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>85</column-width>
	</column-params>
	<column-params>
		<column-name>itemQty</column-name>
		<column-title>Item Qty</column-title>
		<class-name>java.lang.Integer</class-name>
		<column-width>85</column-width>
	</column-params>
	<column-params>
		<column-name>uomQty</column-name>
		<column-title>UOM Qty</column-title>
		<class-name>java.lang.Integer</class-name>
		<column-width>85</column-width>
	</column-params>
</crown-report>

=== gvgreat/hrillekha/crown/retail/crown-retail/src/main/java/com/techlords/crown/mvc/reports/config/audit-report.xml
<?xml version="1.0" encoding="UTF-8"?>
<crown-report xmlns="http://www.techlords.com/crown-report"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.techlords.com/crown-report crown-report.xsd ">
	<bean-name>CrownAuditBO</bean-name>
	<title>Audit Report</title>
	<sub-title>Audit Report for all Entities</sub-title>
	<margin>20</margin>
	<detail-height>15</detail-height>
	<column-params>
		<column-name>tableName</column-name>
		<column-title>Entity Name</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>85</column-width>
		<criteria-column>true</criteria-column>
	</column-params>
	<column-params>
		<column-name>crownUser</column-name>
		<column-title>User</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>85</column-width>
	</column-params>
	<column-params>
		<column-name>action</column-name>
		<column-title>Action</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>85</column-width>
	</column-params>
	<column-params>
		<column-name>description</column-name>
		<column-title>Description</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>85</column-width>
	</column-params>
	<column-params>
		<column-name>timestamp</column-name>
		<column-title>Time Stamp</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>85</column-width>
	</column-params>
</crown-report>

=== gvgreat/hrillekha/crown/retail/crown-retail/src/main/java/com/techlords/crown/mvc/reports/config/invoice-report.xml
<?xml version="1.0" encoding="UTF-8"?>
<crown-report xmlns="http://www.techlords.com/crown-report"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.techlords.com/crown-report crown-report.xsd ">
	<bean-name>InvoiceBO</bean-name>
	<title>Invoice Report</title>
	<sub-title>Invoice Report for all Invoice States</sub-title>
	<margin>20</margin>
	<detail-height>15</detail-height>
	<column-params>
		<column-name>invoiceStateName</column-name>
		<column-title>Invoice State</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>60</column-width>
		<criteria-column>true</criteria-column>
	</column-params>
	<column-params>
		<column-name>invoiceNumber</column-name>
		<column-title>Invoice Number</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>60</column-width>
	</column-params>
	<column-params>
		<column-name>invoiceDate</column-name>
		<column-title>Invoice Date</column-title>
		<class-name>java.util.Date</class-name>
		<column-width>60</column-width>
	</column-params>
	<column-params>
		<column-name>finalInvoiceAmount</column-name>
		<column-title>Invoice Amount</column-title>
		<class-name>java.lang.Double</class-name>
		<column-width>60</column-width>
	</column-params>
	<column-params>
		<column-name>paymentStatusName</column-name>
		<column-title>Payment Status</column-title>
		<class-name>java.lang.String</class-name>
		<column-width>60</column-width>
	</column-params>
	<column-params>
		<column-name>totalPaidAmount</column-name>
		<column-title>Paid Amount</column-title>
		<class-name>java.lang.Double</class-name>
		<column-width>60</column-width>
	</column-params>
</crown-report>
