=== gvgreat/hrillekha/crown/retail/crown-retail/src/main/java/com/techlords/crown/mvc/flow/crown-flow.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.techlords.com/crown-flow" xmlns:tns="http://www.techlords.com/crown-flow"
	elementFormDefault="qualified">
	<xs:element name="crown-flow">
		<xs:annotation>
			<xs:documentation>Crown Flow involved in cases where there is a
				business
				flow to go across different states</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="flow-id" type="xs:string" nillable="false"
					maxOccurs="1" />
				<xs:element name="flow-class" type="xs:string" nillable="false"
					maxOccurs="1" />
				<xs:element ref="tns:flow-steps" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- FLOW STEPS -->
	<xs:element name="flow-steps">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:step" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- STEPS -->
	<xs:element name="step">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="step-id" type="xs:int" nillable="false"
					maxOccurs="1" />
				<xs:element name="step-name" type="xs:string" nillable="false"
					maxOccurs="1" />
				<xs:element name="step-description" type="xs:string"
					maxOccurs="1" />
				<xs:element name="first-step" type="xs:boolean"
					maxOccurs="1" minOccurs="0" />
				<xs:element name="next-step-id" type="xs:int"
					maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gvgreat/hrillekha/crown/retail/crown-retail/src/main/java/com/techlords/crown/mvc/flow/invoice-process-flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:crown-flow xmlns:tns="http://www.techlords.com/crown-flow"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.techlords.com/crown-flow crown-flow.xsd ">
	<tns:flow-id>InvoiceFlow</tns:flow-id>
	<tns:flow-class>InvoiceBO</tns:flow-class>
	<tns:flow-steps>
		<tns:step>
			<tns:step-id>1</tns:step-id>
			<tns:step-name>GENERATED</tns:step-name>
			<tns:step-description>Invoice Created</tns:step-description>
			<tns:first-step>true</tns:first-step>
			<tns:next-step-id>2</tns:next-step-id>
		</tns:step>
		<tns:step>
			<tns:step-id>2</tns:step-id>
			<tns:step-name>PRINTED</tns:step-name>
			<tns:step-description>Original Invoice Printed.</tns:step-description>
			<tns:next-step-id>3</tns:next-step-id>
			<tns:next-step-id>4</tns:next-step-id>
			<tns:next-step-id>5</tns:next-step-id>
			<tns:next-step-id>6</tns:next-step-id>
		</tns:step>
		<tns:step>
			<tns:step-id>3</tns:step-id>
			<tns:step-name>DELIVERED</tns:step-name>
			<tns:step-description>Order Delivered</tns:step-description>
			<tns:next-step-id>8</tns:next-step-id>
		</tns:step>
		<tns:step>
			<tns:step-id>4</tns:step-id>
			<tns:step-name>RETURNED</tns:step-name>
			<tns:step-description>Items Returned</tns:step-description>
			<tns:next-step-id>7</tns:next-step-id>
		</tns:step>
		<tns:step>
			<tns:step-id>5</tns:step-id>
			<tns:step-name>CANCELLED</tns:step-name>
			<tns:step-description>Order cancelled/Items shall be completely returned.</tns:step-description>
			<tns:next-step-id>7</tns:next-step-id>
		</tns:step>
		<tns:step>
			<tns:step-id>6</tns:step-id>
			<tns:step-name>PARTIAL_DELIVERY</tns:step-name>
			<tns:step-description>Order Partially Delivered</tns:step-description>
			<tns:next-step-id>7</tns:next-step-id>
		</tns:step>
		<tns:step>
			<tns:step-id>7</tns:step-id>
			<tns:step-name>CREDIT_NOTE</tns:step-name>
			<tns:step-description>Credit Note released</tns:step-description>
			<tns:next-step-id>8</tns:next-step-id>
		</tns:step>
		<tns:step>
			<tns:step-id>8</tns:step-id>
			<tns:step-name>CLOSED</tns:step-name>
			<tns:step-description>Invoice Closed. No further process</tns:step-description>
		</tns:step>
	</tns:flow-steps>
</tns:crown-flow>

=== gvgreat/hrillekha/crown/retail/crown-retail/src/main/java/com/techlords/crown/mvc/flow/stock-movement-flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:crown-flow xmlns:tns="http://www.techlords.com/crown-flow"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.techlords.com/crown-flow crown-flow.xsd ">
	<tns:flow-id>StockFlow</tns:flow-id>
	<tns:flow-class>StockMovementBO</tns:flow-class>
	<tns:flow-steps>
		<tns:step>
			<tns:step-id>1</tns:step-id>
			<tns:step-name>MOVED</tns:step-name>
			<tns:step-description>Stock Movement Initiated</tns:step-description>
			<tns:first-step>true</tns:first-step>
			<tns:next-step-id>3</tns:next-step-id>
			<tns:next-step-id>4</tns:next-step-id>
			<tns:next-step-id>5</tns:next-step-id>
		</tns:step>
		<tns:step>
			<tns:step-id>2</tns:step-id>
			<tns:step-name>RETURNED</tns:step-name>
			<tns:step-description>Stock is Returned; It may be closed after verification qty.</tns:step-description>
			<tns:next-step-id>6</tns:next-step-id>
		</tns:step>
		<tns:step>
			<tns:step-id>3</tns:step-id>
			<tns:step-name>ACCEPTED</tns:step-name>
			<tns:step-description>Stock Accepted; It may be closed</tns:step-description>
			<tns:next-step-id>6</tns:next-step-id>
		</tns:step>
		<tns:step>
			<tns:step-id>4</tns:step-id>
			<tns:step-name>PARTIAL_ACCEPT</tns:step-name>
			<tns:step-description>Stock Partially Accepted</tns:step-description>
			<tns:next-step-id>2</tns:next-step-id>
		</tns:step>
		<tns:step>
			<tns:step-id>5</tns:step-id>
			<tns:step-name>CANCELLED</tns:step-name>
			<tns:step-description>Stock Movement cancelled; This may be returned and closed.</tns:step-description>
			<tns:next-step-id>2</tns:next-step-id>
		</tns:step>
		<tns:step>
			<tns:step-id>6</tns:step-id>
			<tns:step-name>CLOSED</tns:step-name>
			<tns:step-description>Moved Step; Initial</tns:step-description>
		</tns:step>
	</tns:flow-steps>
</tns:crown-flow>
